#!/bin/bash
cp main_worm molSimplify.app/Contents/MacOS/molSimplify
cp -R ../Bind molSimplify.app/Contents/Resources/
cp -R ../Cores molSimplify.app/Contents/Resources/
cp -R ../Data molSimplify.app/Contents/Resources/
cp -R ../icons molSimplify.app/Contents/Resources/
cp -R ../Ligands molSimplify.app/Contents/Resources/
cp -R ../Bind Distribute_ubuntu/
cp -R ../Cores Distribute_ubuntu/
cp -R ../Data Distribute_ubuntu/
cp -R ../icons Distribute_ubuntu/
cp -R ../Ligands Distribute_ubuntu/
cp -R ../Bind Distribute_source/
cp -R ../Cores Distribute_source/
cp -R ../Data Distribute_source/
cp -R ../icons Distribute_source/
cp -R ../Ligands Distribute_source/
cp -R ../Scripts Distribute_source/
cp -R ../Classes Distribute_source/
cp -R ../main.py Distribute_source/
cp -R ../pybel.py Distribute_source/
